#include "timecore_hal.h"
#include "systemclock/systemclock.h"


/* ============================================================
 * Private Configuration
 * ============================================================ */

/*
 * TimeCore software tick frequency.
 *
 * Defines how many timer update events occur per second.
 *
 * 1000 Hz = 1 ms time base.
 */
#define TIMECORE_TICK_FREQ_HZ      1000UL


/*
 * Timer counter frequency.
 *
 * Defines the operating frequency of the selected timer counter.
 *
 * 1 MHz = 1 us counter resolution.
 */
#define TIMECORE_COUNTER_FREQ_HZ   1000000UL


/* ============================================================
 * Private Module State
 * ============================================================ */

static volatile uint32_t timecore_subsecond = 0U;
static volatile uint8_t  timecore_updateFlag = 0U;


/* ============================================================
 * Private Functions
 * ============================================================ */

static void TimeCore_HAL_EnableClock(void)
{
    TIMECORE_HAL_TIMER_ENABLE();
}


static uint32_t TimeCore_HAL_GetTimerClock(void)
{
    return SystemClock_GetFrequency();
}


static void TimeCore_HAL_ConfigureTimer(void)
{
    uint32_t timer_clock;
    uint32_t prescaler;

    timer_clock = TimeCore_HAL_GetTimerClock();

    /*
     * Timer counter frequency:
     *
     *      1 MHz = 1 us resolution
     */

    prescaler =
        (timer_clock / TIMECORE_COUNTER_FREQ_HZ) - 1UL;

    TIMECORE_HAL_TIMER_INSTANCE->PSC = prescaler;

    /*
     * Update frequency:
     *
     *      1 MHz / 1000 = 1 kHz
     *
     * Therefore:
     *
     *      1 update event = 1 ms
     */

    TIMECORE_HAL_TIMER_INSTANCE->ARR =
        (TIMECORE_COUNTER_FREQ_HZ /
         TIMECORE_TICK_FREQ_HZ) - 1UL;

    TIMECORE_HAL_TIMER_INSTANCE->CNT = 0U;
}


static void TimeCore_HAL_ConfigureInterrupt(void)
{
    /*
     * Generate update event.
     *
     * This loads the PSC value.
     */

    TIMECORE_HAL_TIMER_INSTANCE->EGR = TIM_EGR_UG;

    /*
     * Clear update interrupt flag generated by UG.
     */

    TIMECORE_HAL_TIMER_INSTANCE->SR &= ~TIM_SR_UIF;

    /*
     * Enable update interrupt.
     */

    TIMECORE_HAL_TIMER_INSTANCE->DIER |= TIM_DIER_UIE;

    /*
     * Enable NVIC interrupt.
     */

    NVIC_EnableIRQ(TIMECORE_HAL_TIMER_IRQn);
}


/* ============================================================
 * Public Interface
 * ============================================================ */

void TimeCore_HAL_Init(void)
{
    /*
     * Stop timer during configuration.
     */

    TIMECORE_HAL_TIMER_INSTANCE->CR1 = 0U;


    /*
     * Enable timer peripheral clock.
     */

    TimeCore_HAL_EnableClock();


    /*
     * Configure timer base.
     */

    TimeCore_HAL_ConfigureTimer();


    /*
     * Configure interrupt.

     */

    TimeCore_HAL_ConfigureInterrupt();


    /*
     * Start timer.
     */

    TIMECORE_HAL_TIMER_INSTANCE->CR1 |= TIM_CR1_CEN;
}


uint32_t TimeCore_HAL_GetMs(void)
{
    return timecore_subsecond;
}


void TimeCore_HAL_ResetMs(void)
{
    timecore_subsecond = 0U;
}


void TimeCore_HAL_ClearUpdateFlag(void)
{
    timecore_updateFlag = 0U;
}


uint8_t TimeCore_HAL_GetUpdateFlag(void)
{
    return timecore_updateFlag;
}


/* ============================================================
 * Common Interrupt Handler
 * ============================================================ */

void TimeCore_HAL_IRQHandler(void)
{
    if ((TIMECORE_HAL_TIMER_INSTANCE->SR & TIM_SR_UIF) != 0U)
    {
        /*
         * Clear timer update flag.
         */

        TIMECORE_HAL_TIMER_INSTANCE->SR &= ~TIM_SR_UIF;


        /*
         * Increment millisecond counter.
         */

        timecore_subsecond++;


        /*
         * Set software update flag.
         */

        timecore_updateFlag = 1U;
    }
}


/* ============================================================
 * Timer Interrupt Vector
 * ============================================================ */

#if (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM1)

void TIM1_UP_TIM16_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM2)

void TIM2_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM3)

void TIM3_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM4)

void TIM4_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM5)

void TIM5_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM6)

void TIM6_DAC_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM7)

void TIM7_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM8)

void TIM8_UP_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM15)

void TIM15_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM16)

void TIM1_UP_TIM16_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM17)

void TIM1_TRG_COM_TIM17_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}


#elif (TIMECORE_HAL_TIMER == TIMECORE_HAL_TIMER_TIM20)

void TIM20_UP_IRQHandler(void)
{
    TimeCore_HAL_IRQHandler();
}

#endif